### ISSUE TITLE
How to get openstreetmap.osm.pbf data

### ISSUE THREAD

**Issue by w8128835** [iisys-hof/map-matching-2#6]
It seems a great work!!! I want to run this program by .image file,and i have 2 questions:
1.I downloaded  map_matching_2-1.0.4-x86_64.AppImage ,after chmod +x to make it executable，can I try to run it as below command？
./map_matching_2-1.0.4-x86_64.AppImage --prepare --file openstreetmap.osm.pbf --output data/network/
./map_matching_2-1.0.4-x86_64.AppImage --match --input data/network --tracks data/tracks.csv --output data/results
2.If I can run it as question 1's command,where can i get the file openstreetmap.osm.pbf ? I didn't find it in this repo
![image](https://github.com/user-attachments/assets/b6e7836c-7174-47b2-ae2b-7f522a33a8db)

Thanks for your work again ^_^

**Comment by addy90** [comment]
Hi @w8128835,
thank you for your question!

Concerning question 1: Yes the commands look valid, however, these are only the base commands, you certainly might need additional arguments depending on your tracks.csv file. Please consult the [help.txt](https://github.com/iisys-hof/map-matching-2/blob/main/help.txt) (especially the `CSV Options`) and the [data](https://github.com/iisys-hof/map-matching-2/tree/main/data) examples folder for more insights. You can pass arguments either via a conf file or via CLI parameters by adding `--` to them and replacing the `=` with a space. You can see this for example with the `--file` and `--output` parameters when you compare the base commands with the example [prepare.conf](https://github.com/iisys-hof/map-matching-2/blob/main/data/floating-car-data/conf/prepare.conf) and [match.conf](https://github.com/iisys-hof/map-matching-2/blob/main/data/floating-car-data/conf/match.conf) files, for example, from the [floating-car-data](https://github.com/iisys-hof/map-matching-2/tree/main/data/floating-car-data) example. So it is interchangeable, whatever fits your needs better.

Concerning question 2:
I added an explanation about where to get OpenStreetMap data in the main README: [Download OpenStreetMap data extracts](https://github.com/iisys-hof/map-matching-2?tab=readme-ov-file#download-openstreetmap-data-extracts).
I really should have given this information before, great question!
There exist multiple providers where you can get the extract that you need. Don't hesitate to download an extract that is somewhat larger than your track (as long as it is reasonable, a complete region for a city is no issue, but a whole country for only a small city needs a lot more time to import). The matching part does not become slower with a larger region, only the import takes more time.
Most providers allow for multiple boundary levels to download from. Just select the smallest one that is still sufficiently larger than your track and you should be good.

If you have any further questions, feel free to ask!

**Comment by w8128835** [comment]
I will check the wiki and try it,thank you very much!
